/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductTypeService } from "../productType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductTypeCreateInput } from "./ProductTypeCreateInput";
import { ProductType } from "./ProductType";
import { ProductTypeFindManyArgs } from "./ProductTypeFindManyArgs";
import { ProductTypeWhereUniqueInput } from "./ProductTypeWhereUniqueInput";
import { ProductTypeUpdateInput } from "./ProductTypeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductTypeControllerBase {
  constructor(
    protected readonly service: ProductTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductType })
  @nestAccessControl.UseRoles({
    resource: "ProductType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProductType(
    @common.Body() data: ProductTypeCreateInput
  ): Promise<ProductType> {
    return await this.service.createProductType({
      data: data,
      select: {
        createdAt: true,
        desciption: true,
        id: true,
        name: true,
        normalizedName: true,
        notes: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductType] })
  @ApiNestedQuery(ProductTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productTypes(@common.Req() request: Request): Promise<ProductType[]> {
    const args = plainToClass(ProductTypeFindManyArgs, request.query);
    return this.service.productTypes({
      ...args,
      select: {
        createdAt: true,
        desciption: true,
        id: true,
        name: true,
        normalizedName: true,
        notes: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productType(
    @common.Param() params: ProductTypeWhereUniqueInput
  ): Promise<ProductType | null> {
    const result = await this.service.productType({
      where: params,
      select: {
        createdAt: true,
        desciption: true,
        id: true,
        name: true,
        normalizedName: true,
        notes: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProductType(
    @common.Param() params: ProductTypeWhereUniqueInput,
    @common.Body() data: ProductTypeUpdateInput
  ): Promise<ProductType | null> {
    try {
      return await this.service.updateProductType({
        where: params,
        data: data,
        select: {
          createdAt: true,
          desciption: true,
          id: true,
          name: true,
          normalizedName: true,
          notes: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProductType(
    @common.Param() params: ProductTypeWhereUniqueInput
  ): Promise<ProductType | null> {
    try {
      return await this.service.deleteProductType({
        where: params,
        select: {
          createdAt: true,
          desciption: true,
          id: true,
          name: true,
          normalizedName: true,
          notes: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
